// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import "@openzeppelin/contracts/utils/Pausable.sol";
import "@openzeppelin/contracts/access/extensions/AccessControlEnumerable.sol";

/**
 * @title UniBridgeVault
 * @notice A professional-grade cross-chain bridge contract.
 * @dev Implements Role-Based Access Control (RBAC), Replay Protection, and Emergency Stops.
 */
contract UniBridgeVault is AccessControlEnumerable, ReentrancyGuard, Pausable {
    // --- Roles ---
    // The RELAYER_ROLE is responsible for executing the release transactions on the target chain.
    bytes32 public constant RELAYER_ROLE = keccak256("RELAYER_ROLE");

    // --- State Variables ---
    // Mapping to prevent Replay Attacks. Tracks unique transaction IDs that have been processed.
    mapping(bytes32 => bool) public processedNonces;

    // --- Events ---
    // Emitted when a user locks funds on the source chain.
    // Indexers/Relayers listen for this event to trigger the release on the destination chain.
    event Locked(
        address indexed sender,
        uint256 amount,
        uint256 targetChainId,
        uint256 nonce,
        uint256 timestamp
    );

    // Emitted when funds are released to the user on this chain.
    event Released(
        address indexed recipient,
        uint256 amount,
        bytes32 indexed transactionId
    );

    /**
     * @dev Constructor grants the deployer both Admin and Relayer roles initially.
     * In production, the Admin should revoke their own Relayer role after setting up the backend nodes.
     */
    constructor() {
        _grantRole(DEFAULT_ADMIN_ROLE, msg.sender);
        _grantRole(RELAYER_ROLE, msg.sender);
    }

    /**
     * @notice Locks assets on the current chain to bridge them to a target chain.
     * @dev Generates a unique hash (transactionId) to ensure traceability.
     * @param _targetChainId The Chain ID of the destination network (e.g., 56 for BSC).
     * @param _nonce A unique number generated by the frontend to prevent duplication.
     */
    function lock(
        uint256 _targetChainId,
        uint256 _nonce
    ) external payable nonReentrant whenNotPaused {
        require(msg.value > 0, "Amount must be greater than 0");

        // Generate a unique ID for this specific transaction
        // We include the block.chainid to ensure IDs are unique across different source networks
        bytes32 transactionId = keccak256(
            abi.encodePacked(msg.sender, _targetChainId, _nonce, block.chainid)
        );

        // Check replay protection
        require(!processedNonces[transactionId], "Transfer already processed");

        // Mark as processed
        processedNonces[transactionId] = true;

        emit Locked(
            msg.sender,
            msg.value,
            _targetChainId,
            _nonce,
            block.timestamp
        );
    }

    /**
     * @notice Releases assets to the user.
     * @dev This function is RESTRICTED. Only an address with RELAYER_ROLE can call it.
     * This pattern separates the 'Admin' (who manages roles) from the 'Relayer' (who executes daily tasks).
     * @param _recipient The user who should receive the funds.
     * @param _amount The amount of native currency (ETH/BNB/TRX) to release.
     * @param _transactionId The unique hash generated on the source chain (for tracking and replay protection).
     */
    function release(
        address payable _recipient,
        uint256 _amount,
        bytes32 _transactionId
    ) external onlyRole(RELAYER_ROLE) nonReentrant whenNotPaused {
        // 1. Check for Replay Attack
        require(
            !processedNonces[_transactionId],
            "Transaction already processed"
        );
        // 2. Check Liquidity
        require(
            address(this).balance >= _amount,
            "Insufficient bridge liquidity"
        );
        // 3. Mark transaction as processed (State Change)
        processedNonces[_transactionId] = true;
        // 4. Transfer Funds (Interaction)
        (bool success, ) = _recipient.call{value: _amount}("");
        require(success, "Transfer failed");

        emit Released(_recipient, _amount, _transactionId);
    }

    // --- Admin Functions ---

    /**
     * @notice Pauses all bridge operations (Lock and Release) in case of a security incident.
     * @dev Restricted to DEFAULT_ADMIN_ROLE.
     */
    function pause() external onlyRole(DEFAULT_ADMIN_ROLE) {
        _pause();
    }

    /**
     * @notice Resumes bridge operations.
     * @dev Restricted to DEFAULT_ADMIN_ROLE.
     */
    function unpause() external onlyRole(DEFAULT_ADMIN_ROLE) {
        _unpause();
    }

    /**
     * @notice Emergency function to withdraw trapped funds.
     * @dev Useful if the bridge is deprecated or if funds were sent by mistake.
     * @param _amount The amount to withdraw.
     */
    function emergencyWithdraw(
        uint256 _amount
    ) external onlyRole(DEFAULT_ADMIN_ROLE) nonReentrant {
        require(address(this).balance >= _amount, "Insufficient balance");

        (bool success, ) = payable(msg.sender).call{value: _amount}("");
        require(success, "Transfer failed");
    }

    // --- view Functions ---
    /**
     * @notice Returns all addresses that have been granted a specific role.
     * @param role The bytes32 identifier of the role (e.g., RELAYER_ROLE).
     */
    function getRoleMembers(
        bytes32 role
    ) public view override returns (address[] memory) {
        uint256 count = getRoleMemberCount(role);
        address[] memory members = new address[](count);

        for (uint256 i = 0; i < count; i++) {
            members[i] = getRoleMember(role, i);
        }

        return members;
    }

    function getAllRelayers() external view returns (address[] memory) {
        return getRoleMembers(RELAYER_ROLE);
    }

    function getAllAdmins() external view returns (address[] memory) {
        return getRoleMembers(DEFAULT_ADMIN_ROLE);
    }

    /**
     * @notice Allows the contract to receive ETH/BNB to refill liquidity.
     * @dev The Relayer or Liquidity Providers can send funds here directly.
     */
    receive() external payable {}
}
